import {
  AlarmClock,
  BellRing,
  CalendarCheck2,
  CalendarClock,
  CalendarRange,
  CheckSquare2,
  Flag,
  ListTodo,
  Sparkles,
  StickyNote,
  PanelsTopLeft,
  Utensils,
  CloudSun,
} from "lucide-react";
import {
  CalendarWidget,
  ClockWidget,
  DdayWidget,
  MemoWidget,
  MealWidget,
  NotificationWidget,
  PriorityTaskWidget,
  QuickLauncherWidget,
  TodaySummaryWidget,
  TodayTasksWidget,
  UpcomingWidget,
  WeeklyWidget,
  WeatherWidget,
} from "../widgets";
import type { WidgetCategory, WidgetDefinition, WidgetType } from "./types";
import { widgetTypes } from "./types";

export const widgetRegistry = {
  clock: {
    type: "clock",
    title: "날짜·시계",
    description: "현재 날짜와 시간을 실시간으로 표시합니다.",
    category: "basic",
    component: ClockWidget,
    icon: AlarmClock,
    defaultSize: { w: 3, h: 2 },
    minW: 2,
    minH: 2,
    maxW: 5,
    maxH: 3,
    singleton: true,
  },
  "today-summary": {
    type: "today-summary",
    title: "오늘의 보건실",
    description: "오늘 일정, 업무, 미완료, D-Day 요약을 봅니다.",
    category: "basic",
    component: TodaySummaryWidget,
    icon: Sparkles,
    defaultSize: { w: 5, h: 2 },
    minW: 4,
    minH: 2,
    maxW: 6,
    maxH: 3,
    singleton: true,
  },
  "priority-task": {
    type: "priority-task",
    title: "지금 해야 할 일",
    description: "가장 중요한 업무와 남은 시간을 강조합니다.",
    category: "basic",
    component: PriorityTaskWidget,
    icon: ListTodo,
    defaultSize: { w: 4, h: 2 },
    minW: 3,
    minH: 2,
    maxW: 5,
    maxH: 3,
    singleton: true,
  },
  "monthly-calendar": {
    type: "monthly-calendar",
    title: "월간 실무일정",
    description: "교육, 검진, 행사, 보고 일정을 월간 달력으로 봅니다.",
    category: "schedule",
    component: CalendarWidget,
    icon: CalendarRange,
    defaultSize: { w: 5, h: 7 },
    minW: 4,
    minH: 5,
    maxW: 8,
    maxH: 9,
    singleton: true,
  },
  "today-tasks": {
    type: "today-tasks",
    title: "오늘의 보건업무",
    description: "오늘 처리할 보건업무 체크리스트입니다.",
    category: "work",
    component: TodayTasksWidget,
    icon: CheckSquare2,
    defaultSize: { w: 4, h: 5 },
    minW: 3,
    minH: 3,
    maxW: 6,
    maxH: 8,
    singleton: true,
  },
  "quick-memo": {
    type: "quick-memo",
    title: "빠른 메모",
    description: "현재 실행 중에만 유지되는 임시 메모입니다.",
    category: "work",
    component: MemoWidget,
    icon: StickyNote,
    defaultSize: { w: 4, h: 2 },
    minW: 3,
    minH: 2,
    maxW: 6,
    maxH: 4,
    singleton: true,
  },
  "quick-launcher": {
    type: "quick-launcher",
    title: "빠른 실행",
    description: "자주 쓰는 기능과 이 기기의 업무 폴더를 엽니다.",
    category: "work",
    component: QuickLauncherWidget,
    icon: PanelsTopLeft,
    defaultSize: { w: 3, h: 3 },
    minW: 3,
    minH: 3,
    maxW: 5,
    maxH: 5,
    singleton: true,
  },
  "upcoming-schedule": {
    type: "upcoming-schedule",
    title: "주요 일정",
    description: "가까운 주요 일정 5건을 봅니다.",
    category: "schedule",
    component: UpcomingWidget,
    icon: CalendarClock,
    defaultSize: { w: 3, h: 4 },
    minW: 3,
    minH: 3,
    maxW: 5,
    maxH: 6,
    singleton: true,
  },
  dday: {
    type: "dday",
    title: "D-Day",
    description: "다가오는 제출과 행사를 D-Day로 확인합니다.",
    category: "schedule",
    component: DdayWidget,
    icon: Flag,
    defaultSize: { w: 3, h: 2 },
    minW: 2,
    minH: 2,
    maxW: 5,
    maxH: 4,
    singleton: true,
  },
  "weekly-schedule": {
    type: "weekly-schedule",
    title: "이번 주 실무일정",
    description: "월요일부터 일요일까지 이번 주 업무를 훑어봅니다.",
    category: "schedule",
    component: WeeklyWidget,
    icon: CalendarCheck2,
    defaultSize: { w: 8, h: 3 },
    minW: 5,
    minH: 3,
    maxW: 12,
    maxH: 5,
    singleton: true,
  },
  notifications: {
    type: "notifications",
    title: "알림",
    description: "보건실 업무 관련 알림을 표시합니다.",
    category: "work",
    component: NotificationWidget,
    icon: BellRing,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 2,
    maxW: 5,
    maxH: 5,
    singleton: true,
  },
  meal: {
    type: "meal",
    title: "오늘의 급식",
    description: "등록 학교의 오늘 급식 메뉴를 확인합니다.",
    category: "basic",
    component: MealWidget,
    icon: Utensils,
    defaultSize: { w: 3, h: 3 },
    minW: 3,
    minH: 3,
    maxW: 5,
    maxH: 5,
    singleton: true,
  },
  weather: {
    type: "weather",
    title: "오늘의 날씨",
    description: "등록 학교의 현재 날씨를 확인합니다.",
    category: "basic",
    component: WeatherWidget,
    icon: CloudSun,
    defaultSize: { w: 3, h: 2 },
    minW: 3,
    minH: 2,
    maxW: 5,
    maxH: 3,
    singleton: true,
  },
} as const satisfies Record<WidgetType, WidgetDefinition>;

export const widgetDefinitions = widgetTypes.map((type) => widgetRegistry[type]);

export const widgetLibraryCategories = [
  { id: "basic", title: "기본" },
  { id: "schedule", title: "일정" },
  { id: "work", title: "업무" },
] as const satisfies readonly { readonly id: WidgetCategory; readonly title: string }[];

export const assertWidgetRegistryIntegrity = (): void => {
  const registeredTypes = widgetDefinitions.map((definition) => definition.type);
  const uniqueTypes = new Set(registeredTypes);

  if (registeredTypes.length !== widgetTypes.length || uniqueTypes.size !== widgetTypes.length) {
    throw new Error("위젯 registry 타입 수가 widgetTypes와 일치하지 않습니다.");
  }

  for (const type of widgetTypes) {
    if (!uniqueTypes.has(type)) {
      throw new Error(`위젯 registry에 누락된 타입이 있습니다: ${type}`);
    }
  }
};
